// Presentation details share the existing app's state and actions.
(()=>{
 const $=s=>document.querySelector(s);
 let gateway=null,refresh=null,checking=false;
 const settings=state=>`<div class="preferences"><section class="preferences-banner"><img src="assets/canonical-mark.svg" alt=""><div><span class="eyebrow">YOUR WORKSPACE, YOUR WAY</span><h2>A place that feels like yours.</h2><p>Small adjustments. A better everyday experience.</p></div></section><div class="preferences-heading"><h2>Appearance & interaction</h2><p>Choose how your workspace moves and responds.</p></div><section class="panel preferences-group"><div class="setting"><span><strong>Interface motion</strong><small class="sub" id="motion-note">Gentle transitions and tactile button feedback.</small></span><wa-switch id="interface-motion" aria-label="Interface motion" checked></wa-switch></div><div class="setting"><span><strong>Brand animation</strong><small class="sub">A brief animation of your workspace mark.</small></span><wa-button id="replay-motion" size="small">Replay</wa-button></div></section><div class="preferences-heading"><h2>Opening & closing</h2><p>Predictable behavior, every time you use the app.</p></div><section class="panel preferences-group"><label class="setting"><span><strong>Open when Windows starts</strong><small class="sub">Bring your workspace up when you sign in.</small></span><input id="startup" type="checkbox" ${state.startup?'checked':''}></label><label class="setting"><span><strong>Keep running after closing</strong><small class="sub">${state.closeToTray?'The X button hides the app in your system tray.':'The X button fully quits the app. Background services stay separate.'}</small></span><input id="close-tray" type="checkbox" ${state.closeToTray?'checked':''}></label></section><div class="preferences-heading"><h2>Your data</h2><p>Your work belongs to you.</p></div><section class="panel preferences-group"><div class="setting"><span><strong>Export workspace backup</strong><small class="sub">Save conversations, tasks, notes, and preferences to a file.</small></span><wa-button id="export" size="small">Export backup</wa-button></div></section><div class="preferences-about"><span data-brand="productName"></span><span>Version 0.5.0 · Windows desktop</span></div></div>`;
 function paintConnection(){const d=$('#connection-dialog');if(!d)return;$('#connection-state').textContent=checking?'Checking connection':gateway?.ok?'Connected to Sparky':gateway?'Sparky is unavailable':'Connection not checked';$('#connection-detail').textContent=checking?'Contacting your local assistant. You can keep using your workspace.':gateway?.ok?'Your assistant is available from this PC. Conversations use your existing Sparky connection.':'Your saved workspace is still available. Check the connection again when Sparky is ready.';$('#connection-check').disabled=checking;$('#connection-check').textContent=checking?'Checking…':'Check again';d.dataset.connected=String(!!gateway?.ok);}
 function mount(){document.body.insertAdjacentHTML('beforeend',`<dialog id="connection-dialog" aria-labelledby="connection-title"><form method="dialog"><button class="dialog-close" type="button" aria-label="Close connection details">Close</button></form><img class="connection-icon" src="assets/agents.svg" alt=""><span class="eyebrow">YOUR CONNECTION</span><h2 id="connection-title">Sparky, within reach.</h2><div class="connection-row"><span>Personal assistant</span><strong id="connection-state"></strong></div><p id="connection-detail"></p><div class="connection-actions"><span>Tasks and notes work offline.</span><button id="connection-check">Check again</button></div></dialog>`);$('.dialog-close').addEventListener('click',()=>$('#connection-dialog').close());$('#connection-check').addEventListener('click',async()=>{checking=true;paintConnection();try{await refresh?.();}finally{checking=false;paintConnection();}});$('#gateway-badge').setAttribute('aria-haspopup','dialog');$('#gateway-badge').addEventListener('click',e=>{e.stopImmediatePropagation();paintConnection();$('#connection-dialog').showModal();},true);$('#connection-dialog').addEventListener('click',e=>{if(e.target===$('#connection-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});}
 function render(){document.querySelectorAll('nav button').forEach(b=>{b.setAttribute('aria-current',b.classList.contains('active')?'page':'false');});$('#sidebar-toggle').setAttribute('aria-expanded',String(!document.body.classList.contains('sidebar-collapsed')));$('#sidebar-toggle').title='Show or hide sidebar';$('#send')?.setAttribute('title','Send message (Enter)');const input=$('#chat-input');if(input){const update=()=>{const send=$('#send');if(send)send.disabled=!!document.querySelector('.thinking')||!input.value.trim();};input.addEventListener('input',update);update();}document.querySelectorAll('.avatar-button').forEach(b=>b.title='Workspace settings');}
 window.appFinish={settings,render,connect(fn){refresh=fn;mount();},gateway(value){gateway=value;paintConnection();},ready(){document.body.classList.remove('is-starting');$('#startup-screen')?.remove();},failed(){const p=$('#startup-copy');if(p)p.textContent='Your workspace could not be opened. Try again to reload your saved data.';$('#startup-retry').hidden=false;}};
 document.addEventListener('click',e=>{if(e.target.id==='startup-retry')location.reload();});
 document.addEventListener('change',e=>{if(e.target.id==='close-tray'){e.target.closest('.setting').querySelector('small').textContent=e.target.checked?'The X button hides the app in your system tray.':'The X button fully quits the app. Background services stay separate.';}});
})();
